services:
  api:
    build: ./backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  postgres:
    image: postgres:15
    env_file:
      - ./.env
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
