services:
  frontend:
    image: node:24-slim
    container_name: ai_fitness_tracker_frontend
    working_dir: /app
    volumes:
      - ./frontend/ai-fitness-tracker:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  api:
    build: ./backend
    container_name: ai_fitness_tracker_app
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
      - ./.env

  postgres:
    image: postgres:17.5
    container_name: postgres_db
    env_file:
      - ./.env
    ports:
    - "5432:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
